language: node_js
node_js:
  - "stable"
install:
    - npm ci
cache:
  directories:
    - "$HOME/.npm"
services:
  - postgresql
addons:
  postgresql: "11.3"
before_script:
  - psql --version
  - psql -c "create database teamwork_test;" -U postgres
  - psql -c "create role travis SUPERUSER LOGIN CREATEDB;" -U postgres
  - psql -f db/000001.sql -d teamwork_test
  - psql -f db/000002.sql -d teamwork_test
  - psql -f db/000003.sql -d teamwork_test
  - psql -f db/000004.sql -d teamwork_test
  - psql -f db/000005.sql -d teamwork_test
after_script:
  - npm run coverage
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11 